## PyTorch Fundamentals

### Tensor Basics

In [1]:
import torch
import numpy as np

Tensors (Multi-Dimensional Matrices)

In [5]:
x = torch.Tensor(5, 3)
# OR 
# x = torch.rand(5, 3)
print(x)


 0.1949  0.0000  0.1949
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]



Creating a Uniform Distribution

In [16]:
torch.Tensor(5, 3).uniform_(-1, 1)


 0.0405  0.6277  0.5522
 0.9683  0.7477 -0.6963
 0.0499 -0.1973 -0.1760
 0.5687  0.5238  0.4893
 0.6741  0.4687  0.5762
[torch.FloatTensor of size 5x3]

Size

In [6]:
print(x.size())

torch.Size([5, 3])


Addition

In [7]:
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))


 0.3524  0.9941  0.5052
 0.8402  0.4396  0.2559
 0.1516  0.3136  0.8176
 0.8022  0.2979  0.1485
 0.0600  0.8662  0.5225
[torch.FloatTensor of size 5x3]


 0.3524  0.9941  0.5052
 0.8402  0.4396  0.2559
 0.1516  0.3136  0.8176
 0.8022  0.2979  0.1485
 0.0600  0.8662  0.5225
[torch.FloatTensor of size 5x3]



Getting Result as a Tensor

This will return the sum into result variable

In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.3524  0.9941  0.5052
 0.8402  0.4396  0.2559
 0.1516  0.3136  0.8176
 0.8022  0.2979  0.1485
 0.0600  0.8662  0.5225
[torch.FloatTensor of size 5x3]



In Place Addition

In place functions are followed by an _

In [9]:
y.add_(x)
print(y)


 0.3524  0.9941  0.5052
 0.8402  0.4396  0.2559
 0.1516  0.3136  0.8176
 0.8022  0.2979  0.1485
 0.0600  0.8662  0.5225
[torch.FloatTensor of size 5x3]



Indexing, Slicing

In [11]:
print(x[:, 1])
# Excercise: Try other slicing techniques here


1.00000e-41 *
  4.5595
  0.0000
  0.0000
  0.0000
  0.0000
[torch.FloatTensor of size 5]



Reshaping

In [41]:
y = torch.randn(5, 10, 15)
print(y.size())
print(y.view(-1, 15).size())  # OR y.view(50, 15)
print(y.view(-1, 15).unsqueeze(1).size()) # Adds a dimension at index 1.

torch.Size([5, 10, 15])
torch.Size([50, 15])
torch.Size([50, 1, 15])


### Tensor Types


source: http://pytorch.org/docs/master/tensors.html

|Data|type|Tensor|
|--- |:--:| ----:|
|32-bit|floating point|torch.FloatTensor|
|64-bit|floating point|torch.DoubleTensor|
|16-bit|floating point|torch.HalfTensor|
|8-bit|integer (unsigned)|torch.ByteTensor|
|8-bit|integer (signed)|torch.CharTensor|
|16-bit|integer (signed)|torch.ShortTensorb|
|32-bit|integer (signed)|torch.IntTensor|
|64-bit|integer (signed)|torch.LongTensor|

In [37]:
int_tensor = torch.IntTensor(2,2)
int_tensor


 1.0449e+09  3.2538e+04
 5.7330e+07  0.0000e+00
[torch.IntTensor of size 2x2]

In [38]:
float_tensor = torch.FloatTensor(2,2)
float_tensor


 0.1949  0.0000
 0.0000  0.0000
[torch.FloatTensor of size 2x2]

In [39]:
byte_tensor = torch.ByteTensor(2,2)
byte_tensor


 136  155
  71   62
[torch.ByteTensor of size 2x2]

In [24]:
a = np.ones((2,2),dtype=np.int32)
a_torch = torch.from_numpy(a)
a_torch


 1  1
 1  1
[torch.IntTensor of size 2x2]

### Numpy Bridge

In [12]:
a = torch.ones(5)
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

In [13]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


### PyTorch Bridge

In [14]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



### Using GPU
Moving the Tensors to GPU

In [15]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

### Autograd

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

autograd.Variable is the central class of the package. It wraps a Tensor, and supports nearly all of operations defined on it. Once you finish your computation you can call .backward() and have all the gradients computed automatically.

You can access the raw tensor through the .data attribute, while the gradient w.r.t. this variable is accumulated into .grad.

![](img/auto.png)

In [25]:
import torch
from torch.autograd import Variable

In [26]:
x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

w = Variable(torch.Tensor([1.0]),  requires_grad=True)  

Requires grad = Allows us to Calculate Gradients

Implement Forward Pass

Multiply the Input Tensor X with the weight Tensor W

In [29]:
def forward(x):
    return x * w

# After training
print("predict (after training)",  4, forward(4).data[0])

	grad:  1.0 2.0 -2.0
	grad:  2.0 4.0 -7.840000152587891
	grad:  3.0 6.0 -16.228801727294922
progress: 0 7.315943717956543
	grad:  1.0 2.0 -1.478623867034912
	grad:  2.0 4.0 -5.796205520629883
	grad:  3.0 6.0 -11.998146057128906
progress: 1 3.9987640380859375
	grad:  1.0 2.0 -1.0931644439697266
	grad:  2.0 4.0 -4.285204887390137
	grad:  3.0 6.0 -8.870372772216797
progress: 2 2.1856532096862793
	grad:  1.0 2.0 -0.8081896305084229
	grad:  2.0 4.0 -3.1681032180786133
	grad:  3.0 6.0 -6.557973861694336
progress: 3 1.1946394443511963
	grad:  1.0 2.0 -0.5975041389465332
	grad:  2.0 4.0 -2.3422164916992188
	grad:  3.0 6.0 -4.848389625549316
progress: 4 0.6529689431190491
	grad:  1.0 2.0 -0.4417421817779541
	grad:  2.0 4.0 -1.7316293716430664
	grad:  3.0 6.0 -3.58447265625
progress: 5 0.35690122842788696
	grad:  1.0 2.0 -0.3265852928161621
	grad:  2.0 4.0 -1.2802143096923828
	grad:  3.0 6.0 -2.650045394897461
progress: 6 0.195076122879982
	grad:  1.0 2.0 -0.24144840240478516
	grad:  2.0 4.0 -0.

Loss

Loss is defined as the difference of prediction and our Estimate

In [30]:
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

Training our NN

Training a NN involves calculating Gradients and changing weights based on Backpropagation

In [35]:
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        #print("grad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data

        # Manually zero the gradients after updating weights
        w.grad.data.zero_()

    print("progress epoch    Losst", epoch, l.data[0])

progress epoch    Losst 0 2.3283064365386963e-10
progress epoch    Losst 1 1.2028067430946976e-10
progress epoch    Losst 2 5.820766091346741e-11
progress epoch    Losst 3 3.842615114990622e-11
progress epoch    Losst 4 2.2737367544323206e-11
progress epoch    Losst 5 1.4551915228366852e-11
progress epoch    Losst 6 5.6843418860808015e-12
progress epoch    Losst 7 3.637978807091713e-12
progress epoch    Losst 8 3.637978807091713e-12
progress epoch    Losst 9 2.0463630789890885e-12


Credits:

http://github.com/pytorch/examples

https://github.com/vinhkhuc/PyTorch-Mini-Tutorials/blob/master/0_multiply.py